export const API_URL = 'https://api.arcana.nomoredomainsicu.ru';
// export const API_URL = 'http://localhost:3102';
export const MOVIES_API_URL = 'https://api.nomoreparties.co';
export const MOVIES_PER_PAGE_DESKTOP = 16;
export const MOVIES_MORE_DESKTOP = 4;
export const MOVIES_PER_PAGE_TABLET = 8;
export const MOVIES_MORE_TABLET = 4;
export const MOVIES_PER_PAGE_MOBILE = 5;
export const MOVIES_MORE_MOBILE = 2;
